import {StyleSheet} from 'react-native';
import COLORS from '../../Assets/Style/Color';
export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: '5%',
  },
  Headsection: {
    // backgroundColor: COLORS.primary,
    // height: 150,
    paddingVertical: '4%',
    // paddingHorizontal: '5%',
    borderBottomColor: COLORS.border_color,
    borderBottomWidth: 2,
    // backgroundColor: 'coral',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  Headsection__one: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // position: 'absolute',
    // top: 20,
    // width: '105%',
  },
  Headsection__second__lefts: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#757575',
    // position: 'absolute',
    // left: -15,
    // top: 30,
  },
  Headsection__second__right: {
    // position: 'absolute',
    // right: 20,
    height: 50,
    width: 50,
    backgroundColor: COLORS.icon_bg_color,
    justifyContent: 'center',
    alignContent: 'center',
    borderRadius: 30,
    // marginTop: 10,
  },
  avatarimage: {width: '100%', height: '100%', borderRadius: 30},
  // Body__heading: {fontWeight: 'bold', fontSize: 20, color: COLORS.dark},
  Body__paragraph: {fontSize: 17, top: 4, color: '#757575'},
  Hdate: {
    fontSize: 17,
    top: 4,
    color: '#757575',
    fontWeight: 'bold',
  },
  date: {
    fontSize: 17,
    top: 4,
    color: '#757575',
    marginLeft: 10,
  },
  footericon: {
    flexDirection: 'column',
    width: '35%',
    justifyContent: 'center',
    paddingTop: '3%',
    left: 10,
  },
  Footer: {
    borderTopColor: COLORS.border_color,
    borderTopWidth: 2,
    borderBottomColor: COLORS.border_color,
    borderBottomWidth: 2,
    height: 80,
    marginTop: '15%',
    marginBottom: 20,
  },
});
